# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name:  Static Code Analysis

on: workflow_dispatch
    
jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2

      - name: Zip Sources for Static Analysis
        run: yarn build:sources
        
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          appname: 'Portal Frontend'
          createprofile: false
          filepath: 'portal-frontend.zip'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}' 
